
---
title: "Binary to continuous methodology draft"
date: "`r Sys.Date()`"
output: 
    pdf_document:
        latex_engine: xelatex
urlcolor: blue
bibliography: allocation.bib 
header-includes:
   - \usepackage{amsmath}
   - \usepackage{algorithm}
   - \usepackage[noend]{algpseudocode}
   - \usepackage{amsthm}
   - \usepackage{bm}
   - \usepackage{cases}
   - \usepackage{caption}
   - \usepackage{unicode-math}
   - \usepackage{hyperref}
   - \DeclareMathOperator*{\argmin}{argmin}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE, 
    message = FALSE, 
    warning = FALSE,
    fig.width=10, 
    fig.height=6)
library(tidyverse)
library(patchwork)
```
<!-- $ ...to toggle Latexyz math scope off -->
\newcommand{\del}[2]{\frac{\partial {#1} }{\partial {#2}} }
\newcommand{\dby}[2]{\frac{d {#1} }{d {#2}} }
\newcommand{\sbar}{\overline{s}}
\newtheorem{proposition}{Proposition}

\theoremstyle{remark}
\newtheorem*{remark}{Remark}



We begin with a basic task in public health: triage at the unit level, that is, the problem of deciding to whom, where, and when a unit of scarce health-care resource is allocated. We assume that the resource unit, e.g., a bed, ventillator, dose, or clinician, is indivisible, and that a potential recipient is a single person during a single period of time (say, a day).  We also focus on the scenario of a recipient that is not yet under care, such as a person that may be infected with SARS-COV-2 in the future and consequently require hospitalization or intubation. 

A decision problem is...

Unit-level decision problem: allocate to potential case in location $a$ or $b$. With a decision variable $d$ we write this as $d=a$ or $d=b$.

- elicit forecast $P(Y_a=1) = p$ where $Y_a=1$ if a case in addition to what is currently provided for at horizon $h$ occurs during the day at horizon $h$ in $a$, and 0 otherwise.  $p$ can in particular come from a distributional incidence forecast $F_a$ via $p = 1-F_a(x)$ where $x$ is the number of cases currently provided for in $h$ days.

- fix prob $\beta$ of additional case in $b$, via

	- baseline/persistence/climatology, or

	- $F_b$ taken as a given, not to be evaluated, or

	- $F_{\sum i \neq a}(x) = \int_{\mathbb{R}^n}\mathbb{1}\{\sum_{i \neq a} x_i \leq x\}dF$ if $b$ is a collection of locations and $F$ is a given joint distribution for all coations other than $a$.

We define a loss function for the decision problem that encodes the dilemma faced when balancing the risk of a case of unmet need in $a$ incurred when $d=b$ is chosen against the guaranteed "average" unmet need of $\beta$ in $b$ that is incurred when $d=a$ is chosen. This is the function of the decision $d$ and outcome $Y_a$ 
$$
l(d,Y) = \mathbb{1}\{d=a\}\beta + \mathbb{1}\{d=b\}Y_a,
$$
which picks one of the 4 entries in the table
$$
\begin{array}{rcc}
\text{New case in $a$:}& \text{Yes} & \text{No} \\
\hline
\begin{array}{cr}
\text{allocate to:} & 
\begin{array}{cc}
a \\
b
\end{array}
\end{array}
&
\begin{array}{cc}
\beta \\
1
\end{array}
&
\begin{array}{cc}
\beta \\
0
\end{array}
\end{array}
$$

Associated with this loss function is the *regret* function 
$$
r(d,Y) = \mathbb{1}\{d=a\}\beta + (\mathbb{1}\{d=b\} - \beta)Y_a,
$$
with tabular form
$$
\begin{array}{rcc}
\text{New case in $a$:}& \text{Yes} & \text{No} \\
\hline
\begin{array}{cr}
\text{allocate to:} & 
\begin{array}{cc}
a \\
b
\end{array}
\end{array}
&
\begin{array}{cc}
0 \\
1 - \beta
\end{array}
&
\begin{array}{cc}
\beta \\
0
\end{array}
\end{array}
$$
This encodes the allocation dilemma in terms of how much worse our decision is than that of an oracle that only allocates to $a$ when $Y_a=1$. 

According to the forecast $p$, the decision has expected loss and regret
\begin{align}
E_{p}[l(d)] &=  \mathbb{1}\{d=a\}\beta + \mathbb{1}\{d=b\}p \\
E_{p}[r(d)] &=  \mathbb{1}\{d=a\}\beta + (\mathbb{1}\{d=b\} - \beta)p 
\end{align}
which are minimized by the decision rule
$$
d(p) = 
\begin{cases}
a & \text{if  } p > \beta \\
b & \text{otherwise}.
\end{cases}
$$
This decision --- or *Bayes* --- rule allows us to convert $l$ and $r$ into a scoring functions
\begin{align}
s_l(p,Y_a) &= l(d(p),Y_a) = \mathbb{1}\{p > \beta\}\beta +\mathbb{1}\{p \leq \beta\}Y_a  \\
s_r(p,Y_a) &= s_l(p,Y_a) - \beta Y_a
\end{align}


- Show, a la Ehm eqs 13-16 that integrating over $x$ gives a Brier score for any $\beta$

	- relate to quantile score for $F_a$

- Show how looking at different $\beta$ with $x$ fixed gives a *value* or *Murphy* curve

	- integrating over $x$ now gives CRPS...











